jax_env: False

seed: 0
algo: sac
verbose: 1
# Environment configuration
env:
  env_id: "PointMazeTest-v0"
  max_episode_steps: 300
  num_envs: 8
  jax_env: False
  env_kwargs:
    render_mode: "rgb_array"
    reward_type: "sparse"
eval_env:
  num_envs: 4
  max_episode_steps: 300

sac:
  num_seed_steps: 5_000
  seed_with_policy: False
  replay_buffer_capacity: 1_000_000
  batch_size: 512
  steps_per_env: 1
  grad_updates_per_step: 80
  actor_update_freq: 20

  num_qs: 10
  num_min_qs: 2

  discount: 0.99
  tau: 0.005
  backup_entropy: False

  eval_freq: 5_000
  eval_steps: 1000

  log_freq: 1000
  save_freq: 500

  learnable_temp: True
  initial_temperature: 1.0
  
network:
  actor:
    type: "mlp"
    arch_cfg:
      features: [256, 256, 256]
      output_activation: "relu"
  critic:
    type: "mlp"
    arch_cfg:
      features: [256, 256, 256]
      output_activation: "relu"
      use_layer_norm: True

train:
  actor_lr: 3e-4
  critic_lr: 3e-4
  steps: 1_000_000
  dataset_path: "demos/pointmaze3/trajectory.h5"
  shuffle_demos: True
  num_demos: 1000

  data_action_scale: null

  ## Reverse curriculum configs
  reverse_step_size: 8
  start_step_sampler: "geometric"
  curriculum_method: "per_demo"
  per_demo_buffer_size: 2
  demo_horizon_to_max_steps_ratio: 1

  load_actor: True
  load_critic: True
  load_as_offline_buffer: True
  load_as_online_buffer: False

  ## Forward curriculum configs
  forward_curriculum: "success_once_score"
  staleness_coef: 0.1
  staleness_temperature: 0.1
  staleness_transform: "rankmin"
  score_transform: "rankmin"
  score_temperature: 0.1

  num_seeds: 34
logger:
  tensorboard: True
  wandb: False

  workspace: "exps"
  project_name: "RFCL-PointMaze"
  wandb_cfg:
    group: "RFCL-PointMaze"
