base_config: "base_sac_ms2_sample_efficient.yml"
env:
  env_id: "PickCube-v0"
sac:
  discount: 0.9
train:
  dataset_path: "demos/mani_skill2/v0/rigid_body/PickCube-v0/trajectory.state.pd_ee_delta_pose.h5"
